name: Build TopSkyMSAW

on:
  push:
    branches:
      - main
    paths:
      - ".data/TopSkyMSAW/**"
      - ".github/workflows/concatenate_TopSkyMSAW.py"
      - ".github/workflows/build_TopSkyMSAW.yml"

  pull_request:
    paths:
      - ".data/TopSkyMSAW/**"
      - ".github/workflows/concatenate_TopSkyMSAW.py"
      - ".github/workflows/build_TopSkyMSAW.yml"

concurrency:
  group: TopSkyMSAW-Compile
  cancel-in-progress: true

jobs:
  compile:
    name: Compile TopSkyMSAW Data Files
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run compiler
        run: python .github/scripts/TopSkyMSAW/concatenate_TopSkyMSAW.py

      - name: Commit compiled files
        run: |
          git config user.name  'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git add "OEJD/Plugins/TopSky/TopSkyMSAW.txt" "OEJD/Plugins/TopSky - ACC/TopSkyMSAW.txt"

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Compile TopSkyMSAW data files"

          git push